// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcylhSe9PBMlZFbLfZCSZY8c0BF1pS4VA',
    appId: '1:650915165332:web:4c80d6eb9bf3521af07081',
    messagingSenderId: '650915165332',
    projectId: 'skillshare-app-a7a4d',
    authDomain: 'skillshare-app-a7a4d.firebaseapp.com',
    storageBucket: 'skillshare-app-a7a4d.firebasestorage.app',
    measurementId: 'G-SX43VEKV8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3WOtOH0iDhVM03o8T6nQze1obUGf1yDk',
    appId: '1:650915165332:android:280f081825d59d43f07081',
    messagingSenderId: '650915165332',
    projectId: 'skillshare-app-a7a4d',
    storageBucket: 'skillshare-app-a7a4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnqMaW2AFnOYG_oTId6I3f1YAu3Uz_g7s',
    appId: '1:650915165332:ios:3df968951fe14720f07081',
    messagingSenderId: '650915165332',
    projectId: 'skillshare-app-a7a4d',
    storageBucket: 'skillshare-app-a7a4d.firebasestorage.app',
    iosBundleId: 'com.example.skillshareFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnqMaW2AFnOYG_oTId6I3f1YAu3Uz_g7s',
    appId: '1:650915165332:ios:3df968951fe14720f07081',
    messagingSenderId: '650915165332',
    projectId: 'skillshare-app-a7a4d',
    storageBucket: 'skillshare-app-a7a4d.firebasestorage.app',
    iosBundleId: 'com.example.skillshareFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcylhSe9PBMlZFbLfZCSZY8c0BF1pS4VA',
    appId: '1:650915165332:web:c9ad3b709a4a1bacf07081',
    messagingSenderId: '650915165332',
    projectId: 'skillshare-app-a7a4d',
    authDomain: 'skillshare-app-a7a4d.firebaseapp.com',
    storageBucket: 'skillshare-app-a7a4d.afirebasestorage.app',
    measurementId: 'G-T18Z0L6FRY',
  );
}
